### ISSUE TITLE
Swift 2.2.1 build fails on MacOS High Sierra

### ISSUE THREAD

**Issue by leanne63** [kylef/swiftenv#103] opened 2017-11-03 18:48 UTC
Swift 3.1.1 installed perfectly first try. Been through a few iterations, though, trying to install 2.2.1.

Installed CMake 3.9.4, Ninja 1.8.2, then Python 3.6.3. Seemed to almost make it through - then failed again, and I'm not sure what's happening with this one.

I'd appreciate any help you can offer! Here is the end of my log, starting with the failure:

```
[136/665] Building CXX object lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenProfiling.cpp.o
FAILED: lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenProfiling.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/SILGen -I/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/swift/lib/SILGen -I/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/swift/include -Iinclude -I/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/build/Ninja-ReleaseAssert/llvm-macosx-x86_64/include -I/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/llvm/include -I/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/build/Ninja-ReleaseAssert/llvm-macosx-x86_64/tools/clang/include -I/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/llvm/tools/clang/include -I/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/cmark/src -I/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/build/Ninja-ReleaseAssert/cmark-macosx-x86_64/src -fno-stack-protector -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wcovered-switch-default -Wnon-virtual-dtor -Werror=date-time -std=c++11 -fcolor-diagnostics -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -O3    -UNDEBUG  -fno-exceptions -fno-rtti -target x86_64-apple-macosx10.9 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -arch x86_64 -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/../../../Developer/Library/Frameworks -mmacosx-version-min=10.9 -O2 -momit-leaf-frame-pointer -g0 -UNDEBUG -MD -MT lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenProfiling.cpp.o -MF lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenProfiling.cpp.o.d -o lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenProfiling.cpp.o -c /Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/swift/lib/SILGen/SILGenProfiling.cpp
In file included from /Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/swift/lib/SILGen/SILGenProfiling.cpp:13:
In file included from /Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/swift/lib/SILGen/SILGenProfiling.h:16:
In file included from /Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/llvm/include/llvm/ADT/DenseMap.h:17:
In file included from /Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/llvm/include/llvm/ADT/DenseMapInfo.h:17:
In file included from /Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/llvm/include/llvm/ADT/ArrayRef.h:13:
In file included from /Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/llvm/include/llvm/ADT/Hashing.h:48:
In file included from /Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/build/Ninja-ReleaseAssert/llvm-macosx-x86_64/include/llvm/Support/DataTypes.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:305:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:309:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1301:38: error: incomplete type 'swift::Expr' used in type trait expression
    : public integral_constant<bool, __is_abstract(_Tp)> {};
                                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1374:39: note: in instantiation of template class 'std::__1::is_abstract<swift::Expr>' requested here
                                     !is_abstract<_T2>::value> {};
                                      ^
/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/swift/include/swift/Basic/NullablePtr.h:40:22: note: in instantiation of template class 'std::__1::is_convertible<swift::Expr, swift::Expr>' requested here
                std::is_convertible<OtherT, T>::value,
                     ^
/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/swift/include/swift/Basic/NullablePtr.h:30:7: note: while substituting deduced template arguments into function template 'NullablePtr' [with OtherT = swift::Expr]
class NullablePtr {
      ^
/Users/username/.swiftenv/tmp/swiftenv-build-2.2.1/swift/include/swift/AST/ASTNode.h:24:9: note: forward declaration of 'swift::Expr'
  class Expr;
        ^
1 error generated.
[137/665] Building CXX object lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenExpr.cpp.o
[138/665] Building CXX object lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenLValue.cpp.o
[139/665] Building CXX object lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenPoly.cpp.o
[140/665] Building CXX object lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenProlog.cpp.o
[141/665] Building CXX object lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenStmt.cpp.o
[142/665] Building CXX object lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenType.cpp.o
[143/665] Building CXX object lib/SILGen/CMakeFiles/swiftSILGen.dir/SILGenPattern.cpp.o
ninja: build stopped: subcommand failed.
./utils/build-script: command terminated with a non-zero exit status 1, aborting

```

**Comment by kylef** [comment] 2017-11-06 09:51
I can reproduce the same on Sierra / Xcode 9.1 / CMake 3.9.4 / ninja 1.8.2.

I added a `#include "swift/AST/Expr.h"` include into  `~/.swiftenv/tmp/swiftenv-build-2.2.1/swift/include/swift/AST/ASTNode.h` and it seemed to solve that particular problem. Although it wasn't long before I hit another compilation problem with undefined symbols referenced from `libLLVMSupport.a` while building the binaries in `bin/`.

It might be worth reaching out on the appropriate Swift mailing lists such as [swift-dev](https://lists.swift.org/mailman/listinfo/swift-dev) regarding the state of Swift 2.2.1 when built with Xcode 9 / High Sierra. swiftenv is just a minimal wrapper around the build process and this looks like a problem on the Swift side.

All `swiftenv` is currently doing is a `./utils/build-script -R -- --install-prefix="$destination"` after downloading the source code(s).

**Comment by kylef** [comment] 2017-11-18 10:22
Did you have any luck @leanne63 ?

**Comment by leanne63** [comment] 2017-11-19 00:22
Got sidetracked - sent a message out to swift-dev today. Hopefully, we'll hear something soon!

**Comment by leanne63** [comment] 2017-11-20 00:58
Slava suggested installing an older Xcode. I have 7.3.1 under a different name, so I switched the Tools (using `xcode-select`), and it still didn't work. Then I noticed in the log that it wasn't using `xcrun`; instead the script is using the default Tools location. So, I renamed my current Xcode.app, renamed my copy of Xcode 7.3.1 to Xcode.app, and tried again. The build worked, then, and I was able to install v2.2.1 successfully.

**Comment by kylef** [comment] 2018-04-19 22:47
I'm wondering how we can make this issue actionable in swiftenv. I am not sure it makes sense to maintain a list of compatible Xcode versions and `swift` in swiftenv and validate when installing. It's a shame that they are so tied together, and even more shame that the swift build scripts do not check for the expected dependencies and environment.

Perhaps we can point to the documentation at https://swift.org/download/#using-downloads for a user to grab the appropriate version of Xcode to build with.

Once upon a time (2016) I sent the following into the swift-evolution mailing list, which unfortunately I never got any response with.

> Hi,
> 
> I've been thinking a lot about the experience building and installing
> Swift from source and being able to package Swift (such as providing
> packages in systems such as emerge, pacman, rpm, apt-get, homebrew,
> etc). As it is, the current process of building and installing Swift
> from source isn't simple or clearly documented and I think there is some
> changes we can do to make it easier for both users to build Swift and
> for package maintainers to package Swift.
> 
> It doesn't seem like there is a great adoption for package maintainers
> providing Swift packages and this could be attributed to it being
> difficult and not clear. One of the goals of this proposal should be to
> increase adoption and availability of Swift on various platforms.
> 
> I'd like to start a discussion on how we can improve this situation as a
> first step for a Swift Evolution proposal on improving the packaging and
> installation of Swift. I'll first give a quick run through of the
> current process and then later go on with how I think we can improve the
> situation.
> 
> Current Process
> ---------------
> 
> The current process of building and installing Swift from source isn't
> very clear, the download page at https://swift.org/download/ doesn't
> include downloading the source, only binaries for a limited amount of
> platforms.
> 
> You can find a source code page at https://swift.org/source-code/ which
> explains the multiple repositories Swift components are distributed
> across, this page will link you to the Swift repositories README for
> instructions on building Swift.
> 
> The README instructions are tied to specific platforms (Ubuntu and
> macOS) and do not clearly list the dependencies. These development
> dependencies do not list dependencies that are already pre-installed on
> the given platforms such as perl. This can make it cumbersome to figure
> out what is required on other platforms.
> 
> To build Swift, you will need to clone various repositories via git.
> There is a script to aid cloning the various repositories and checkout
> out the relevant tag based on the release you are trying to install. You
> need to clone the entire history of Swift to be able to build it, this
> will consume a lot of bandwidth and disk space. Cloning the various git
> repositories will often make it difficult to integrate into package
> systems.
> 
> When it comes to building Swift, this can be problematic if you have
> missed installing some of the dependencies since there isn't a way to
> verify you have everything Swift needs upfront. You can try to build
> Swift, but it may fail after a while with an obscure error which isn't
> clear that you missed a dependency.
> 
> There is no clear instructions on how you can install the version of
> Swift you have built on your system.
> 
> Improvements
> ------------
> 
> I think Swift should provide a complete tarball including all of the
> Swift sources. A user installing Swift should not have to clone the
> entire Swift history and instead download a tarball that contains
> everything they need for a specific version. The tarball should be aimed
> at users who want to build and install Swift but do not want to develop
> Swift.
> 
> The tarball should contain a script (probably similar to a "configure"
> script) which can validate the user has all the needed dependencies.
> 
> There should be a consist method to build and then install Swift and the
> standard library. I think it may be beneficial if these are steps
> consistent with other tools and libraries.
> 
> Documentation and links to each version tarball should be available on
> the Swift website along with detailed list of all the required
> build-time and run-time dependencies and supported versions.

**Comment by kylef** [comment] 2019-06-28 17:21
I'm going to close this issue as there isn't much we can do in swiftenv.

**Closed by kylef** 2019-06-28 17:21 UTC
Labels: question, upstream
